name: Keep Server Awake

on:
  schedule:
    - cron: "0 */2 * * *" # Run every 2 hours

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Make HTTP Request
        run: curl https://car-dealer-f97k.onrender.com
