name: Keep Server Awake

on:
  schedule:
    - cron: "*/20 * * * *" # Run every 20 minutes

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Make HTTP Request
        run: curl https://car-dealer-f97k.onrender.com
